#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("epos.Droid.Resource", IsApplication=true)]

namespace epos.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_close_black_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_dashboard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_discuss = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_done = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_event = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_forum = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_headset = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int btnAddMember = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int btnAuthCode = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btnLogin = 2131165187;
			
			// aapt resource value: 0x7f070019
			public const int btnNewMemberNext = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int editTextNewMemberPhone = 2131165208;
			
			// aapt resource value: 0x7f07000b
			public const int editTxtMulti = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int main_tab_banner = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int memberListView = 2131165190;
			
			// aapt resource value: 0x7f07001a
			public const int menu_save = 2131165210;
			
			// aapt resource value: 0x7f07000a
			public const int multiTextToolbar = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int newMemberListToolbar = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int radio_female = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int radio_male = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int txtAuthCode = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int txtLoginPhone = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int txtName = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int txtPhone = 2131165193;
			
			// aapt resource value: 0x7f070015
			public const int txtViewBirth = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int txtViewBirthValue = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int txtViewExtendInfo = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int txtViewName = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int txtViewNameValue = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int txtViewPhone = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int txtViewPhoneVaue = 2131165198;
			
			// aapt resource value: 0x7f070017
			public const int txtViewRemark = 2131165207;
			
			// aapt resource value: 0x7f070012
			public const int txtViewSex = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int txtViewTextCount = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MemberDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MemberList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MemberListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MultiText = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewMember_Info = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewMember_Phone = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int saveMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
